CREATE TABLE IF NOT EXISTS `xhs_note_comment` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `tenant_id` bigint(20) NOT NULL DEFAULT '1' COMMENT '多租户编号',
  `note_id` varchar(255) NOT NULL DEFAULT '' COMMENT '笔记ID',
  `comment_id` varchar(255) NOT NULL DEFAULT '' COMMENT '评论ID',
  `parent_comment_id` varchar(255) DEFAULT '' COMMENT '父级评论ID',
  `target_comment_id` varchar(255) DEFAULT '' COMMENT '回复的目标评论ID',
  `user_id` varchar(255) DEFAULT '' COMMENT '评论发表者用户ID',
  `nickname` varchar(255) DEFAULT '' COMMENT '评论发表者昵称',
  `red_id` varchar(255) DEFAULT '' COMMENT '小红书号',
  `avatar` varchar(1024) DEFAULT '' COMMENT '用户头像地址',
  `content` text COMMENT '评论正文',
  `ip_location` varchar(128) DEFAULT '' COMMENT 'IP属地',
  `like_count` int(11) DEFAULT '0' COMMENT '点赞数',
  `sub_comment_count` int(11) DEFAULT '0' COMMENT '子评论数',
  `is_author` tinyint(4) DEFAULT '0' COMMENT '是否笔记作者评论：0-否，1-是',
  `pictures` text COMMENT '评论配图链接(JSON数组)',
  `comment_time` varchar(64) DEFAULT '' COMMENT '评论发布时间',
  `intercept_status` tinyint(4) DEFAULT '0' COMMENT '截流跟进状态：0-未触达，1-已发私信，2-已加微信，3-意向偏低/无效',
  `remark` varchar(1024) DEFAULT '' COMMENT '跟进备注',
  `raw_json` longtext COMMENT '原始评论JSON',
  
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_comment_id` (`comment_id`),
  KEY `idx_note_id` (`note_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='小红书笔记评论表';
